### ISSUE TITLE
Enable Photo-Swapping on product page in Shopfy Timber

### ISSUE THREAD

**Issue by corbinjensen** [Shopify/Timber#163]
Hello there,
I am new to shopify and have been using the Timber dev theme for my client.

I am on the product page and instead of the default click and switch to “Grande View”

I want the product to Image swap the feature image.

I read this comment in the product.liquid file:

{% comment %}
If we have more than one product image, loop through them and create thumbnails.

By default, images will link to their grande size (600x600).
Thumbnail swapping is enabled in shop.js.liquid.
{% endcomment %}

So I went over to the shop.js.liquid and perhaps its my unfamiliarity with js but I can’t see where to enable the feature.

Here is the code below from the shop.js.liquid file:

window.timber = window.timber || {};

timber.cache = {
// General
html: $('html'),
body: $('body'),

// Product Page
mainImage: $('#productPhotoImg'),
thumbImages: $('#productThumbs').find('a.product-photo-thumb'),
newImage: null
}

timber.init = function () {
timber.cache.html.removeClass('no-js').addClass('js');

// Run on load
timber.productImageSwitch();
}

timber.productImageSwitch = function () {
if ( !timber.cache.thumbImages.length ) {
return;
}

// Switch the main image with one of the thumbnails
// Note: this does not change the variant selected, just the image
timber.cache.thumbImages.on('click', function(e) {
e.preventDefault();
timber.cache.newImage = $(this).attr('href');
timber.cache.mainImage.attr({ src: timber.cache.newImage });
});
}

// Initialize Timber's JS on docready
$(function() {
window.timber.init();
});

**Comment by CWSites** [comment]
I'm also having the same problem. I compared product to what is in the current release and they are both correct. This is a sample page: http://galilee-of-the-nations.myshopify.com/collections/featured-music/products/who-will-go

**Comment by cshold** [comment]
@CWSites Looks like `shop.js` isn't being loaded. That's Timber's default JS that handles the image switching. Load that after jQuery and that feature will enable itself.

**Comment by CWSites** [comment]
Thanks!
