### ISSUE TITLE
Issue with Ajax Checkout (drawer) expansion

### ISSUE THREAD

**Issue by ginamarr** [Shopify/Timber#167]
On the latest version of Timber, when you have the Ajax drawer enabled, have items in your cart and hit checkout, it does not go to the checkout page, instead the cart expands and is hidden behind the header. 
![screen shot 2014-08-04 at 11 41 52 pm](https://cloud.githubusercontent.com/assets/1128598/3806718/d35a5956-1c52-11e4-85cc-a06cd998c1f7.png)

**Comment by meganraddatz** [comment]
I'm also having this problem now, but in Firefox. Once I manually set the image height to a px value, the problem stopped for me, but it still seems like a weird issue to be having.
