### ISSUE TITLE
Ajaxify stops working when adding infinite-ajax-scroll to shop

### ISSUE THREAD

**Issue by narzero** [Shopify/Timber#254]
Hi there @cshold, 

My Shopify store uses Ajaxify's call's to add products to the cart and jQuery to update the front-end. I recently installed [infinite-ajax-scroll][1] but this brought an issue. 

When scrolling down to the products loaded by infinite-ajax-scroll, and then click on the add to cart button, the ajax calls & jQuery updates don't work anymore, it redirects me to the cart page.

This seems to be common issue and a lot has been written about this but I can't seem to fix it in the Supply theme.

Here's the inline script I'm using to activate IAS:
```
    <script>
      var ias = jQuery.ias({
        container:  '#products',
        item:       '.single-product',
        pagination: '.pagination-custom',
        next:       '.next'
      });
    
      ias.extension(new IASSpinnerExtension({
        src: '{{ "spiffygif_36x36.gif" | asset_url }}'
      }));
    </script>
```
This is the code ([ajaxify.js][2] line 161 - 194) that's responsible for adding the product to the cart:
```
    Shopify.addItemFromForm = function(form, callback, errorCallback) {
      // Unbind IAS
      ias.destroy();
    
      var params = {
        type: 'POST',
        url: '/cart/add.js',
        data: jQuery(form).serialize(),
        dataType: 'json',
        success: function(line_item) {
          if ((typeof callback) === 'function') {
            callback(line_item, form);
          }
          else {
            Shopify.onItemAdded(line_item, form);
          }
        },
        error: function(XMLHttpRequest, textStatus) {
          if ((typeof errorCallback) === 'function') {
            errorCallback(XMLHttpRequest, textStatus);
          }
          else {
            Shopify.onError(XMLHttpRequest, textStatus);
          }
        }
      };
      jQuery.ajax(params);
    
      var variant_id = params.data.split('=')[1]
      $( "#var-id-" + variant_id + " " + "#in-cart-indicator" ).removeClass( "not-in-cart" ).addClass( "triangle-top-right" );
      
      // Bind IAS
      ias.bind();
    };
```

I've added the [`bind`][3] and [`destroy`][4] method based on [this SO post][5], but without success.

What am I doing wrong? Maybe I'm using `bind` and`destroy` on the wrong locations or on the wrong Ajax code.

You can take a look at the page in question [here][6].

Any help would be appreciated!

  [1]: https://github.com/webcreate/infinite-ajax-scroll
  [2]: http://cdn.shopify.com/s/files/1/0656/8697/t/7/assets/ajaxify.js?9064
  [3]: http://infiniteajaxscroll.com/docs/methods.html#bind
  [4]: http://infiniteajaxscroll.com/docs/methods.html#unbind
  [5]: http://stackoverflow.com/questions/20404493/reset-disable-infinite-scroll-after-ajax-call
  [6]: http://goo.gl/AMIgcP

**Comment by cshold** [comment]
Will be addressed with a fix for #255
