### ISSUE TITLE
New fonts do not load properly in IE8

### ISSUE THREAD

**Issue by nickjj** [Shopify/Timber#290]
With IE8 the new font icons only come up after you mouse over them. Prior to the mouse over it uses the fallback text.

**Comment by cshold** [comment]
I'm getting all icons on IE8 Windows 7 32-bit. Can you recheck https://timber-demo.myshopify.com/ please.

![screen shot 2015-01-07 at 11 31 12 am](https://cloud.githubusercontent.com/assets/1730309/5648987/b9cb8bb2-9660-11e4-9a05-263754128f9e.png)


![screen shot 2015-01-07 at 11 29 40 am](https://cloud.githubusercontent.com/assets/1730309/5648956/8056bae6-9660-11e4-8715-3c356b15e41f.png)
