### ISSUE TITLE
Mobile Menu (Responsive)

### ISSUE THREAD

**Issue by robinbirr** [Shopify/Timber#292]
Why is there no Mobile Menu in this theme like Off Canvas or other?
This is a very important thing.

**Comment by spuddick** [comment]
I have been playing around a lot with Timber. I created my own approach to a mobile menu. Take a look at this theme I'm working on (same theme, but different settings):

http://fun-playful-demo.myshopify.com/
https://demo-store-1-21.myshopify.com/
https://elegant-demo.myshopify.com/

I think this goes along nicely at least with the drawer cart animation (if you haven't noticed from other posts I know the drawer pretty well, hehe). I don't think it will fit very well with the other cart animations though.
