### ISSUE TITLE
Variant images: adding a link to the large image

### ISSUE THREAD

**Issue by shoshanna** [Shopify/Timber#306]
When using the variant images feature, is there a suggested method for adding a link to the large image on a product page to open a larger version of the image? For example, if after choosing a variant/thumbnail there needs to be a lightbox link or zoom effect on the large image.

I've tried various methods to get the variants/thumbnails to also change the image link as well as the large image, but I seem to be missing something. Any tips on this would be very helpful. Thanks!

**Comment by cshold** [comment]
The methods we see are usually a lightbox or some sort of zooming action. Both have up and downsides, but the implementation can be pretty similar regardless. I'll give you a quick rundown of our zoom implementation.

Take a look at [this demo](https://react-modern.myshopify.com/products/ambrosia-maple-thin-cutting-board?variant=819258431) from our React theme. When hovering over the product image, a larger one is magnified for you.

Then take a look at [this gist](https://gist.github.com/cshold/e5a6b9c879724bad60f2). In the gist I've stripped React's JS file down to just the image zoom related code. The important part starts at [line 104](https://gist.github.com/cshold/e5a6b9c879724bad60f2#file-shop-js-L104), and you can extend it yourself as needed. Note that we have a theme setting that enables/disables this feature too. At this point we have the new image URL (`src`), and the jQuery object we're updating (`$el`). By setting the `data-zoom` and `src` attributes on our image object, we keep our zoom plugin up to date and reinitialize it each time it changes.

If you want to check out that zoom plugin, the version we tend to use is [here](https://cdn.shopify.com/s/files/1/0641/1153/t/4/assets/jquery.zoom.min.js?1859).
