### ISSUE TITLE
index.liquid contain extra else

### ISSUE THREAD

**Issue by Woland2k** [Shopify/Timber#308]
There is an else statement that corresponds to nothing in index.liquid file.
line 34: {% else %}

It should be removed as it doesn't comply with liquid templates and will break some editors. Probably should be implemented in similar way to how collection section is done underneath with isEmpty variable.

**Comment by cshold** [comment]
If no products exist in the store, the `for` loop is false and the code directly after `else` will run, showing onboarding filler content.

**Comment by Woland2k** [comment]
It seems like that is a non intended side affect functionality as there is no such tag as "for/else" in liquid. There is only "if/else".

**Comment by Woland2k** [comment]
Same error is in collection.list.liquid (there is no "else" in for, not sure how your parser doesn't generate any exception):

      {% for product in collection.products %}

        {% include 'product-list-item' %}

      {% else %}

        <div class="grid__item">
          <p>{{ 'collections.general.no_matches' | t }}</p>
        </div>

      {% endfor %}

**Comment by cshold** [comment]
There is an `else` for for loops, it's just declared advanced. Check it out [here](https://github.com/Shopify/liquid/blob/12d526a05c0654dc67e350f170f91d62fd4875b7/lib/liquid/tags/for.rb#L11).

**Comment by Woland2k** [comment]
Thanks, I can see it now.
