### ISSUE TITLE
Minor UX issue if all products are maxed out

### ISSUE THREAD

**Issue by spuddick** [Shopify/Timber#315]
I've noticed that if you click the 'Add to Cart' button in the main page body, and the product inventory is maxed out, there is a notice indicating that all the products are in the cart. 

However, if you click the 'ajaxcart__qty--plus' button from the shopping cart drawer (I haven't see how this looks on other shopping cart displays) and all products are maxed out, there is no message of any kind to indicate all available products have been added to the cart. It just appears to be unresponsive. Take a look at this example, there are 9 products in the inventory:

https://timber-test-3.myshopify.com/products/all-about-today-learning-board-400

**Comment by cshold** [comment]
This isn't specific to Timber, but rather the API's `Shopify.changeItem` returning successfully after trying to increase the quantity. I'll ping the API team to look into this.

**Comment by cshold** [comment]
@Shopify/api can you look into this?

`Shopify.changeItem` always returns the `cart` data even if the quantity of the product being changed isn't available. It leads to an unresponsive ajax experience.

Recreate it by adding 5 of [this product](https://carson-dev-shop.myshopify.com/collections/cameras/products/canon-eos-rebel-t3-12-2mp-dslr-camera-with-18-55mm-lens-camera-case-memory-card) to the cart. Then once in the drawer, try adding to the quantity.

Possible solutions:
- Return an error (though it's not an ajax error, so not ideal)
- Return cart data with additional parameter with error details

**Comment by cshold** [comment]
@Shopify/api ping

**Comment by cshold** [comment]
Still an issue, but not Timber related so closing this.
