### ISSUE TITLE
Performance of Drawer CSS Transition 

### ISSUE THREAD

**Issue by spuddick** [Shopify/Timber#322]
I have been working on my own theme using Timber, and I believe there is an issue with how the drawer transition works. I have done some tests and it looks like because the height of AjaxifyDrawer is being animated, it is pushing (almost) the entire DOM tree down. This isn't too expensive performance wise with 'bare bones' styling, but once you start adding styles everything starts to add up. In all of these examples I have toggled the cart on and off a few times. Take look at these comparisons (not the prettiest examples, but it gets the point across :) ):

![timber-test-3 myshopify com](https://cloud.githubusercontent.com/assets/5488872/5807778/8b21e9bc-9ff4-11e4-9c14-40143d1a3980.jpg)
http://timber-test-3.myshopify.com: Stock Timber theme. Not too bad performance wise. 

![timber-styled myshopify com](https://cloud.githubusercontent.com/assets/5488872/5807786/a122ad8c-9ff4-11e4-9d07-7ce46112d26b.jpg)
http://timber-styled.myshopify.com: Stock Timber theme with styling. Significant performance decrease.

![timber-styled-drawer-at-bottom](https://cloud.githubusercontent.com/assets/5488872/5807794/b548d520-9ff4-11e4-8c46-55f89c78d9ce.jpg)
http://timber-styled-drawer-at-bottom.myshopify.com: Stock Timber theme with styling, with drawer position at bottom. DOM tree does not have to be moved so performance is very good. 

![timber-styled-refactored myshopify com](https://cloud.githubusercontent.com/assets/5488872/5807800/c29fa14a-9ff4-11e4-8a4d-a9c2d9360036.jpg)
http://timber-styled-refactored.myshopify.com: Stock Timber theme with styling, refactored to increase performance. Take a look at the drawer-transition-test branch I pushed to see exactly what I changed. 

I found this article: http://www.html5rocks.com/en/tutorials/speed/high-performance-animations/ very useful in figuring out what was going on. 

Finally, visually, I can see a big difference in the quality of the animation on iOS devices. Compare all of these examples on an iOS device and you'll see what I mean.

**Comment by spuddick** [comment]
Ah..looks like I can't push to Timber.git. Well, you can take a look with Chrome inspector/Firebug, etc to see what I've done.

**Comment by cshold** [comment]
Great testing and really appreciate it. We're in the early stages of redesigning the ajax cart for a more mobile-friendly approach, and for some alignment with a new mobile navigation. Needless to say performance is a huge consideration that will be at the forefront of the code. The html5rocks link you sent over is invaluable and I'd also highly recommend it for anyone working on transitions.

Because of the new approach coming soon(ish?), we're not going to modify the existing cart transitions.

**Comment by spuddick** [comment]
Glad you found it useful! 

Not sure if saw my other comment in another issue thread, but I am actually working on my own modification to Ajaxify.js to incorporate a mobile nav (as well as other components). I am working on my Shopify application and getting something ready to show you all :). You can take a look at https://demo-store-1-21.myshopify.com/ and see what I have done so far.
