### ISSUE TITLE
Add font-awesome as default icon library

### ISSUE THREAD

**Issue by dillonbailey** [Shopify/Timber#332]

**Comment by cshold** [comment]
Is there a benefit to including 500+ icons for everyone that uses this framework? I don't think most people will use most of the icons most of the time, so the load alone makes it overkill in my opinion.

**Comment by dillonbailey** [comment]
Fair question. Most people will not utilise more than 10 or so of the icons, but I wonder if the standardisation would offer a better opportunity for folks to extend instead of the current custom icons font that is being used?

That also provides a number of icons that someone may or may not use, granted 500 is many more at least these are implemented in a standard fashion across the web.

Not sure the best way to assess which is best.

**Comment by cshold** [comment]
By using IcoMoon's app, you can import the current set and add, remove, or customize the icons as needed. I found this was the best way to provide the basics, allowing customizability (with a bit of work), and keeping performance in mind.

Are there any specific icons you think should be included that aren't? Maybe we can bump up the default collection a bit. I am currently standardizing a few of the icons so they are the same weight and style - they'll be available with the next Timber release.

**Comment by dillonbailey** [comment]
Great suggestion, I was completely unaware of IcoMoon's app. Definitely agree that's the best solution.

I placed a note in the timber.scss.liquid and pull request adding the source of the font icons.

DB

**Comment by cshold** [comment]
Great addition. If you do want to customize the default icon set, import `assets/icons.json` into IcoMoon's app and edit away.

**Comment by HandHugs** [comment]
fontello has great customizable font options as well. It includes icomoons as well as many other great icon libraries.
