### ISSUE TITLE
Adding Ajax cart to related products

### ISSUE THREAD

**Issue by gopinathpara** [Shopify/Timber#340]
Hi Carson!
I'm trying to create ajax add to cart form for related products. this is what i did 
* first i modified the related products code to include add to cart form element . updated related products code 
```
 <script type="text/javascript" charset="utf-8">
//<![CDATA[
  var recommendations = [];
  {% if product.metafields.recommendations.productHandles %}
  recommendations = jQuery.trim({{ product.metafields.recommendations.productHandles | json }}).split(/[\s,;]+/);
  {% endif %}
  if (recommendations.length && recommendations[0] !== '') {
    var list = jQuery('ul.related-products');
    for (var i=0; i<recommendations.length; i++) {
      jQuery.getJSON('/products/' + recommendations[i] + '.js', function(product) {
        list.append('<li class="grid__item large--one-third small--one-whole"><div class=" image"><a href="' + product.url +'"><img src="' + product.images[0].replace(/(\.jpg|\.png|\.jpeg|\.gif)/, '_{{ image_size }}$1') + '" /></a></div><div class="related-info"><h4><a href="' + product.url + '">' + product.title + '</a></h4><span class="money">' + Shopify.formatMoney(product.price, '{{ shop.money_format }}') + '</span><form method="post" action="/cart/add"><input type="hidden" name="id" value="{{ product.variants.first.id }}" /><input type="submit" value="Buy now" class="btn Atc_btn" /></form></div></li>');
      });
    }
  }  
//]]>
</script>
```
* then i added the new button class "Atc_btn" in product.liquid in place of the default submit button id.
*the i updated the new button class in [this line](https://github.com/Shopify/Timber/blob/master/layout/theme.liquid#L196) of theme.liquid 

But it seems like it didn't solve the problem. Can you suggest any way to make this work ?

**Comment by cshold** [comment]
Ah, I didn't realize this was a javascript plugin you were trying to add on to.

You'll have to see if there is a callback function that plugin makes available after its JS runs. That's when you'll initialize the ajax cart found at the bottom of `theme.liquid`. I'd suggest reaching out in our [forums](https://ecommerce.shopify.com/c/ecommerce-design) for some help, as this is outside the scope of Timber.
