### ISSUE TITLE
settings_schema.json

### ISSUE THREAD

**Issue by suture** [Shopify/Timber#345]
It looks like settings_schema.json file is replacing the deprecated settings.html file.
https://docs.shopify.com/themes/theme-development/storefront-editor/settings-schema

**Comment by cshold** [comment]
Yes, that is the new format for our new theme [setting editor](https://docs.shopify.com/manual/your-website/themes/customize). It's just about to be rolled out to 100% one of our shops. When it is, we'll replace it in Timber.
