### ISSUE TITLE
Cannot find documentation on 'push' classes

### ISSUE THREAD

**Issue by carolineschnapp** [Shopify/Timber#349]
What's the proper syntax for "push" in Timber?

I cannot find the info here: http://shopify.github.io/Timber/#sass

Thanks! :)

**Comment by cshold** [comment]
`push--large--one-third`

**Comment by carolineschnapp** [comment]
Thank you Carson! 

CC @NathanPJF :)

**Comment by NathanPJF** [comment]
:+1:

**Comment by cshold** [comment]
Added in https://github.com/Shopify/Timber/commit/75c10841c149e460cd97b016a7191e262c3686d7
