### ISSUE TITLE
Clearfix for grid_uniform children that are breakpoint agnostic

### ISSUE THREAD

**Issue by NathanPJF** [Shopify/Timber#351]
The `@mixin clearfix-helper()` creates **clear:both** declarations for .grid_uniform children that have a breakpoint as part of their class, i.e. `large--one-half`.  But, for .grid_uniform children that don't have a breakpoint specified, there are no css declarations for **clear:both** made.

The result can be seen with our current React theme.  The thumbnails are wrapped in `<li class="grid-item one-quarter">...</li>`.  If a product has more than 4 thumbnails, you'll see this: 

![http://take.ms/AjJcf](http://take.ms/AjJcf)

## Potential fix

Adding the **@include clearfix-helper();** to the "non-responsive width and helper classes" section:

![http://take.ms/U8nE8](http://take.ms/U8nE8)

### Result

![http://take.ms/PXZUb](http://take.ms/PXZUb)

**Comment by NathanPJF** [comment]
@cshold I don't have permissions to make a PR for this, so I was hoping you could take look at my suggested fix.

**Comment by cshold** [comment]
I'll take a look at it. A few other things on my plate today but I'll revisit it soon.

**Comment by NathanPJF** [comment]
No worries, I just did it for a merchant.  It looked good after a quick look through, but we'll see if anything blows up on the site.

**Comment by cshold** [comment]
Well this totally fell off my radar. Rather than trying to build a non-breakpoint clearfix — which I've tried in the past and it was awful with this grid setup — I'd suggest using only breakpoint-specific grid classes, especially in the `grid--uniform` areas like this.

**Comment by NathanPJF** [comment]
:cool:
