### ISSUE TITLE
product.liquid template - changing all variant images at once when a variant is selected? 

### ISSUE THREAD

**Issue by spring-91** [Shopify/Timber#381]
I'm trying to implement a certain feature into my product.liquid template, similar to [this example](http://www.zara.com/uk/en/woman/shorts/belted-chino-shorts-c404505p2503547.html) - if I have a product with 2 variants  and multiple images for those 2 variants, when I click on a different variant I want all of the variant images change together, at the moment I have managed to achieve it but only with the first image. 

What I currently have is from a [tutorial](http://littlesnippets.ca/blogs/tutorials/15665261-grouping-images-with-variants) I found online however as I said above, its only changing the first variant image and not the 2nd/3rd/4th images.

Is there a simpler way of achieving this feature? 

My current template:

    <div itemscope itemtype="http://schema.org/Product">

      <meta itemprop="url" content="{{ shop.url }}{{ product.url }}">
      <meta itemprop="image" content="{{ product.featured_image.src | img_url: 'grande' }}">

      <div class="a4-a9">

        <div class="grid__item large--one-half text-center">

          

          {% assign featured_image = product.selected_or_first_available_variant.featured_image | default: product.featured_image %}
          
          <div class="product-single__photos image featured" id="ProductPhoto">
            <a href="{{ featured_image | img_url: '1024x1024' }}" class="fancybox" rel="gallery1" id="placeholder">
              <img src="{{ featured_image | img_url: '1024x1024' }}" alt="{{ featured_image.alt | escape }}" id="ProductPhotoImg" />
            </a>
          </div>
          

          {% if product.images.size > 1 %}
          
          <ul class="grid-uniform">
            <div class="thumbs clearfix">
            {% assign featured_alt = product.selected_or_first_available_variant.option1 %}
              {% for image in product.images %}
                {% if image.alt == featured_alt or image == featured_image %}
                  {% unless forloop.first %}
                      <li class="image grid_item">
                        <a href="{{ image | img_url: '1024x1024' }}" class="fancybox" rel="gallery1" data-original-image="{{ image | product_img_url: '1024x1024' }}">
                          <img src="{{ image | img_url: '1024x1024' }}" alt="{{ image.alt | escape }}" />
                        </a>
                      </li>
                  {% endunless %}
                {% endif %}
              {% endfor %}
            </div>
          </ul>
          
          {% endif %}

        </div>
        

        <div class="grid__item large--one-half">

          {% if settings.product_vendor_enable%}
            <h3>{{product.vendor | link_to_vendor }}</h3>
          {% endif %}

          <h1 itemprop="name">{{ product.title }}</h1>

          <div itemprop="offers" itemscope itemtype="http://schema.org/Offer">

              <span id="ProductPrice" class="h2{% if product.compare_at_price > product.price %} on-sale{% endif %}" itemprop="price">
                {{ product.price | money }}
              </span>

              {% if product.compare_at_price > product.price %}
                <p id="ComparePrice">
                  {{ 'products.product.compare_at' | t }} {{ product.compare_at_price_max | money }}
                </p>
              {% endif %}

            <div class="product-description rte" itemprop="description">
              {{ product.description }}
            </div>
          
            {% assign variant = product.selected_or_first_available_variant %}

            <meta itemprop="priceCurrency" content="{{ shop.currency }}">

            <link itemprop="availability" href="http://schema.org/{% if product.available %}InStock{% else %}OutOfStock{% endif %}">

            <form action="/cart/add" method="post" enctype="multipart/form-data" id="AddToCartForm">

              <div class="select clearfix"{% if hide_default_title %} style="display: none"{% endif %}>
                <select name="id" id="productSelect" class="product-single__variants">
                  {% for variant in product.variants %}
                    {% if variant.available %}

                      <option {% if variant == product.selected_or_first_available_variant %} selected="selected" {% endif %} value="{{ variant.id }}">{{ variant.title }} - {{ variant.price | money_with_currency }}</option>

                    {% else %}
                      <option disabled="disabled">
                        {{ variant.title }} - {{ 'products.product.sold_out' | t }}
                      </option>
                    {% endif %}
                  {% endfor %}
                </select>

                {% if product.available and product.variants.size > 1 %}
                  {% for option in product.options %}
                    {% include 'swatch' with option %}
                  {% endfor %}
                {% endif %}
              </div>

              <label for="Quantity" class="quantity-selector">{{ 'products.product.quantity' | t }}</label>
              <input type="number" id="Quantity" name="quantity" value="1" min="1" class="quantity-selector">

              <button type="submit" name="add" id="AddToCart" class="btn">
                <span id="AddToCartText">{{ 'products.product.add_to_cart' | t }}</span>
              </button>
            </form>

          </div>

        </div>
      </div>

    </div>

    {{ 'option_selection.js' | shopify_asset_url | script_tag }}

    <script>
      var selectCallback = function(variant, selector) {
          // BEGIN SWATCHES
          if (variant) {
            var form = jQuery('#' + selector.domIdPrefix).closest('form');
            for (var i=0,length=variant.options.length; i<length; i++) {
              var radioButton = form.find('.swatch[data-option-index="' + i + '"] :radio[value="' + variant.options[i] +'"]');
              if (radioButton.size()) {
                radioButton.get(0).checked = true;
              }
            }
          }
        // END SWATCHES
        
        timber.productPage({
          money_format: "{{ shop.money_format }}",
          variant: variant,
          selector: selector
        });
      };

      jQuery(function($) {
        new Shopify.OptionSelectors('productSelect', {
          product: {{ product | json }},
          onVariantSelected: selectCallback,
          enableHistoryState: true
        });

        {% if product.available and product.options.size > 1 %}
          Shopify.linkOptionSelectors({{ product | json }});
        {% endif %}

        // Add label if only one product option and it isn't 'Title'. Could be 'Size'.
        {% if product.options.size == 1 and product.options.first != 'Title' %}
          $('.selector-wrapper:eq(0)').prepend('<label for="productSelect-option-0">{{ product.options.first | escape }}</label>');
        {% endif %}

        // Hide selectors if we only have 1 variant and its title contains 'Default'.
        {% if product.variants.size == 1 and product.variants.first.title contains 'Default' %}
          $('.selector-wrapper').hide();
        {% endif %}
      });
    </script>

    <script>
    jQuery(document).ready(function($){

    var images = [];

    {% for image in product.images %}
      images.push({url: "{{ image | product_img_url: '1024x1024' }}", alt: "{{ image.alt }}"});
    {% endfor %}

      var thumbnails = $(".thumbs");                         
      $('#product-select-option-0').change(function() {
        var selected = $(this).val(), mainImage = jQuery('.featured img').attr('src');
        thumbnails.hide().html("");
        arr = [];

        var addImage = $.each( images, function( i, image ) {
          var alt = images[i].alt, url = images[i].url;   
          if (alt == selected || url == mainImage) {
            thumbnails.append('<li class="grid_item"><a href="' + url + '" data-original-image="' + url + '"><img src="' + url + '" alt="' + alt + '"></a></li>');
          }
        });
        arr.push(addImage);
        var switchImageTwo = function(newImageSrc, newImage, mainImageDomEl) {
          jQuery(mainImageDomEl).attr('src', newImageSrc);
          $(mainImageDomEl).parents('a').attr('href', newImageSrc);
        };
        $.when.apply($, arr).done(function () {
          thumbnails.fadeIn(); 
          $('#product .thumbs a').on('click', function(e) { 
            e.preventDefault();
          switchImageTwo($(this).attr('href'), null, $('.featured img')[0]);
          });
        });
      });
    });    
    </script>

Many thanks in advance!

**Comment by cshold** [comment]
This is better left to our [design forums](https://ecommerce.shopify.com/c/ecommerce-design) as it's not related to Timber specifically.
