### ISSUE TITLE
Issue with cart Drawers (Delay)

### ISSUE THREAD

**Issue by gopinathpara** [Shopify/Timber#384]
I'm using flip method for cart . there is a strange issue with the cart drawer  . when i click on cart in header , it suppose to expand the card from top to bottom but this is some delay in expanding .. 
Browser : Firefox 35.0.1 and 37.0 
Store url : http://goo.gl/Dggc2 

Any help ?

**Comment by cshold** [comment]
That URL isn't a Shopify store so can't help you out here. Feel free to reopen if you can provide the right link.

**Comment by gopinathpara** [comment]
Hi Chris, I'm sorry i pasted wrong url.
here is the correct url http://orangegubbi.com/ 

Thanks

**Comment by cshold** [comment]
You have some JS errors going on so I can't debug it. I'd suggest fixing those so you can reproduce the error and then duplicating the theme in that state. That way you can keep working on your main theme, but there's a sandbox version I can look at.

Copy the link address from the preview button and you'll get a URL like this - http://your=shop.myshopify.com/?preview_theme_id=10585188

![screen shot 2015-03-31 at 10 43 48 am](https://cloud.githubusercontent.com/assets/1730309/6921445/df85d54c-d792-11e4-95f6-1c44e721bad9.png)

**Comment by gopinathpara** [comment]
I've fixed the js errors and you can access the preview site here http://sirius-interior.myshopify.com/?preview_theme_id=10955881 

Thanks :)

**Comment by cshold** [comment]
The delay is there so the cart can load the contents before opening up. This is fixed in a more recent version of Timber, though the changes are quite drastic. The cart opens in a side drawer instead of the top, and the multiple options (modal, flip, drawer) are removed for simplicity.

If you want to get rid of the delay, you could try triggering the cart opening earlier with a loader icon.

**Comment by gopinathpara** [comment]
pardon me  , can you be little more specific 
"If you want to get rid of the delay, you could try triggering the cart opening earlier with a loader icon."

Thanks

**Comment by cshold** [comment]
In `assets/ajaxify.js.liquid` you'll need to write some custom JS in the `loadCartImages` function. This function is called when the cart is loaded, but not yet visible or sized. We do this to make sure the images are loaded so we can get the appropriate height of the entire cart and set it's CSS height property.

Before the `cartImages.on('load')` line, you will have to insert your custom JS to show the drawer at a specific height and a loader icon of your choosing. This part is up to you so I can't be much more specific. I'd also suggest removing the loading icon in the `sizeDrawer` function (which is called after all images have loaded) as you'll no longer need it.
