### ISSUE TITLE
$baseFontSize isn't really customizable

### ISSUE THREAD

**Issue by benknight** [Shopify/Timber#388]
In `timber.scss.liquid` the `em()` function works by dividing a hard pixel value by `$baseFontSize`.  This means that even if you change `$baseFontSize`, anything set using `em()` stays the same size instead of scaling up relative to the base size.

Here's an example: http://sassmeister.com/gist/5844c64c95f0b9d405dc

In my opinion this is a bug because since this is a framework, all font sizes should be relative to the `$baseFontSize` variable.  Right?

**Comment by cshold** [comment]
I'm not sure I follow. If the base font size is 14px, and you want an element set to 18px, using the function would give you nearly 1.3em (like your demo). If the base font size is 18px, and you pass in 18px to the function you're saying "make this element's text the same size as our base font size," which of course is 1em.

That's how I'd expect the function to work. What would you expected outcome be in the demo above?

**Comment by benknight** [comment]
I think understand the confusion here.  I think what I expected was that abstracting font-size to the `em` function would allow you to modify just the base font size variable and have all typography on the site scale accordingly.  However, as `em` is implemented, no matter what $baseFontSize in, `em` will always output a value in `em` that will cause it to be the exact pixel value passed in as the parameter.

In this I ask, what is the point of the `em` function?  Given the browser landscape there is no longer a case for setting all font sizes in em units.  I believe the reason we used to do this was due to inconsistent zoom functionality in browsers, but not all browsers implement "page zoom", allowing authors to set hard pixel values for all text.

Also, if `em` is indeed behaving exactly as intended, then I feel like this framework is missing a mechanism through which authors can set one base font size and have all headings, etc scale accordingly.  Specifically, I'm building a site and instead of having a 14px body font I want to use 18px.  When I set `$baseFontSize` to 18px however, buttons, inputs, headings, etc all stay the same size instead of scaling according to the ratio of 14px/18px.

**Comment by benknight** [comment]
Bump

**Comment by benknight** [comment]
Closing this as invalid, acknowledging that there's actually a strong case still for sizing all text with ems so as not to break a user's font size settings.

**Comment by cshold** [comment]
This hasn't gone unnoticed, don't worry. It's a lower priority right now, but definitely on the list of things to update.

**Comment by benknight** [comment]
Thanks @cshold.  After all I would say this:

There's no bug here.  In my opinion, `em()` is functioning as expected.  I had originally confused the purpose of the `$baseFontSize` / `em()` system as being so that you would only have to adjust `$baseFontSize` variable and all other typography would scale up proportionally, but `em()`'s output stays faithful to its pixel argument regardless of `$baseFontSize`.  This does make changing font sizes a bit tedious since if you want to maintain Timber's proportions, you have to update every single `em()` call site.  In my case I wanted my base font size to be 18px, not 14px, and I wanted my headings to get bigger too.

I think the original intent of using ems was so that you can override the $baseFontSize in a media query and have all text scale accordingly, which is nice.  Using the `rem` unit here instead would add some sanity, since `em`s can get nasty when you're overriding a parent's `em` font size in a child element's styles.
