### ISSUE TITLE
.site-header__cart-toggle switch to inline-block breaks layout?

### ISSUE THREAD

**Issue by pablodelarosa** [Shopify/Timber#392]
Referencing the change committed here:

https://github.com/Shopify/Timber/commit/97018885bc202dec7d9c3a7cd97e51492115d1bd

This makes the cart icon float in the middle of the header whenever the layout is at full width. The icon then goes back to above the search bar once the viewport is less than full width. I'm not sure what the commit was meant to address, as reversing it seems to produce "normal" behavior.

**Comment by cshold** [comment]
With block the element has a phantom clickable area:
![screen shot 2015-04-14 at 5 48 43 pm](https://cloud.githubusercontent.com/assets/1730309/7148164/8cf46e6e-e2ce-11e4-90c3-954c6dd384f6.png)

With inline block:
![screen shot 2015-04-14 at 5 48 53 pm](https://cloud.githubusercontent.com/assets/1730309/7148172/9837bdb2-e2ce-11e4-866b-5d438a079d37.png)

That said, if the account links and search bar aren't in the markup, the layout can break. Best to wrap the element in a div so it's in a block, but doesn't have the large click area.
