### ISSUE TITLE
Close Ajax Cart after set time when adding an item to cart?

### ISSUE THREAD

**Issue by spring-91** [Shopify/Timber#393]
I've implemented Timber with the Ajax slide out cart, but wondered if it's possible to implement some sort of a timer that closes the cart once an item has been added to the cart unless the user is actively interacting with the cart in which case the timer would pause (whilst on hover for example)?

Thanks in advance!

**Comment by cshold** [comment]
That'll be some pretty custom work you'll have to set up yourself, so I can't be too specific with an answer.

You can close the cart with `timber.RightDrawer.close();`. Setup your custom work in a listener like the one below:
```
jQuery('body').on('ajaxCart.afterCartLoad', function(evt, cart) {
  // start timer function

  // when timer is triggered:
  timber.rightDrawer.close();
});
```
