### ISSUE TITLE
Make 'ajaxcart__footer' visible at all times in bottom right of Ajax Cart?

### ISSUE THREAD

**Issue by spring-91** [Shopify/Timber#394]
I'm having a hard time getting my head around how I can adapt the CSS in order to make the product rows of the ajax cart scrollable whilst keeping the Checkout button fixed in the bottom right of the cart so thats its visible at all times.

I know that the scroll is currently applied to '.drawer'. I thought maybe I could wrap a div around the items in the ajax-cart-template.liquid snippet and make them scrollable but I just seem to be breaking it.

I've applied the following to '.ajaxcart__footer' which is working as it should but obviously because its inside '.drawer' its just being fixed inside a scrollable div.

    .ajaxcart__footer {
     position: fixed;
     bottom: 0;
     right: 0;
    }

If this is a simple problem I would appreciate any help you can give.

**Comment by cshold** [comment]
Take a look at the styles on http://carson-dev-shop-2.myshopify.com/. It does exactly what you're looking for. It's a bit too opinionated to be in Timber by default but definitely doable with some adjustments.

**Comment by spring-91** [comment]
Thanks so much, this should help a lot, been stuck on this for a little while!
