### ISSUE TITLE
ajax-cart.js - Extending itemAddedCallback

### ISSUE THREAD

**Issue by lukeclifton** [Shopify/Timber#402]
Hey @cshold.

Thanks for your great work on timber theme.

Could you point me in the right direction on best practice for how to extend / customise the itemAddedCallback function in ajax-cart.js?

I would like to overide this function outside of the ajax.cart.js script...is this possible?

Thanks!

**Comment by cshold** [comment]
You could always replace the function entirely if you want. Anywhere `itemAddedCallback` is referenced, call your (global) function instead.

If you have `myTheme.function` that you want to use, change line 225 to `ShopifyAPI.addItemFromForm(evt.target, myTheme.function, itemErrorCallback);`. 

What are you trying to accomplish with the override and why does it have to be outside of ajax-cart.js? My suggestion above might make no sense depending on your answer.

**Comment by lukeclifton** [comment]
@cshold Thanks for the reply, and sorry for the delay.

I guess i was trying not to make any changes to the ajax-cart.js file, and just override the itemAddedCallback function in my own theme code.

This is my custom itemAddedCallback function, as you can see i'm doing a check based on a hidden input in the form and then redirecting to another page if the input exisits:

```
/* ---------------------------------------------
 * Custom itemAddedCallback function
 * ---------------------------------------------
 * This custom function override is needed to handle the option to redirect to the diamond selector page or not.
 * This would be true if a product with a diamond has just been added.
 * The option is set by the existence of a hidden form input named: redirect_to_diamond_selector
 *
 * The second 'form' param was also added for this itemAddedCallback function so we can get the extra form params
 */
itemAddedCallback = function (product, form) {
		
		// If the form has a hidden input named 'redirect_to_diamond_selector' then we need to redirect to diamond seletor page
		if ($(form).find('[name="redirect_to_diamond_selector"]').length) {

			// Get the form params
			var params = jQuery(form).serialize();

			// Call the diamond selector page
			window.location.replace('/pages/diamond-selector?' + params);

		// Otherwise a normal product has just been added, so just show the normal ajax cart drawer
		} else {

			$addToCart.removeClass('is-adding').addClass('is-added');

			ShopifyAPI.getCart(cartUpdateCallback);
		}
	};
```

I guess its just nesscessary to edit the ajax-cart.js file, right?

**Comment by cshold** [comment]
Yes, that's probably the easiest way to do it. :+1: on the detailed comment too.
