### ISSUE TITLE
Update prefixing mixins

### ISSUE THREAD

**Issue by benknight** [Shopify/Timber#407]
The prefix mixins are doing a bit of unnecessary work:

1. `transition` no longer needs prefixing at all. http://caniuse.com/#search=transition
2. Transforms don't need `-o-` or `-moz-` prefixing: http://caniuse.com/#search=transform
3. Linear gradients no longer need prefixing really, except maybe `-webkit-` for super deep mobile browser support? http://caniuse.com/#search=transform

**Comment by benknight** [comment]
Happy to submit a pull request if authors agree. :)

**Comment by cshold** [comment]
Agreed, I'll :+1: a PR. I was actually thinking of removing the gradient mixin. It's not used anywhere, and I've very rarely been wanting one while developing.

**Comment by graygilmore** [comment]
Looks like this has been taken care of? https://github.com/Shopify/Timber/commit/3ab33cb464f3a8577d70e471587204110f693c85

**Comment by cshold** [comment]
Fixed via #410
