### ISSUE TITLE
Compare at:

### ISSUE THREAD

**Issue by suture** [Shopify/Timber#413]
On the product page. currently the colon in "Compare at:" is hard coded into the timber.js file. 

Should this be part of the translation along with the money value to allow greater flexibility and formatting?

**Comment by cshold** [comment]
Where do you see that? I'm only seeing compare here - https://github.com/Shopify/Timber/blob/master/templates/product.liquid#L99

**Comment by cshold** [comment]
Yup, absolutely. I'll open a quick fix for it.

**Comment by suture** [comment]
In the js file 

https://github.com/Shopify/Timber/blob/master/assets/timber.js.liquid#L247

**Comment by suture** [comment]
Many thanks for that

**Comment by graygilmore** [comment]
Looks like this issue should be closed.
