### ISSUE TITLE
Repodb.yml has a broken link

### ISSUE THREAD

**Issue by acoard** [Shopify/Timber#417]
This is for the current version of the file on line one: https://github.com/Shopify/Timber/blob/master/repodb.yml#L1

Which, gives me a 404.  With a bit of googling I couldn't figure out where it's supposed to be pointing either.  Anyone know?

Thanks.

**Comment by cshold** [comment]
This is an internal Shopify URL to show us the details and structure of `repodb.yml`. There is no public version at this time.
