### ISSUE TITLE
Fire an alert after the LeftDrawer is closed?

### ISSUE THREAD

**Issue by spring-91** [Shopify/Timber#419]
I need to trigger something to happen after the Left Drawer is closed, lets say an alert to keep things simple. I've tried the following but nothing seems to be happening.

```
timber.LeftDrawer.close(function() {
// Do something here...
  alert("Nav drawer closed");
});
```
Am I on the right lines? Apologies as I'm not great with JS.

Any help would be appreciated.

**Comment by cshold** [comment]
Right now there's no function available, but we should be able to create one for you easily. In the `Drawer.prototype.open` method of `assets/timber.js`, we check if `onDrawerOpen` is set, and if it's a function run it. Copy this function into the `Drawer.prototype.close` method with a few changes. Add the following around line 439, after `this.drawerIsOpen = false;`
```
    // Run function when draw opens if set
    if (this.config.onDrawerCLose && typeof(this.config.onDrawerClose) == 'function') {
      this.config.onDrawerClose();
    }
```

Now it's set up to run a function, but we still have to give it one. Up in `timber.drawersInit` (line 184), change `timber.LeftDrawer = new timber.Drawers('NavDrawer', 'left');` to:
```
timber.LeftDrawer = new timber.Drawers('NavDrawer', 'left', {
  'onDrawerClose': yourFunctionName
});
```

Enter any function name there and it'll be called each time the drawer is closed.

**Comment by spring-91** [comment]
Thanks for getting back to me so quickly.

I've made the changes and put the following function in below the `timber.drawersInit` to test to see if it works. I'm getting an alert on page load but then the drawers won't open. Clicking on 'Cart' takes you to the Cart Page.

```
jQuery(function afterClose() {
  alert("Closed");
});
```
Is it something I've done? Have I written the function wrong?

Thanks again.

**Comment by cshold** [comment]
What's your shop URL, I can take a look

**Comment by spring-91** [comment]
Sure its [here.] (http://hatch-inc-tester-store.myshopify.com)

**Comment by cshold** [comment]
You don't need to wrap the afterClose function like that. Just put:
```
function afterClose() {
alert('Closed');
}
```

Right now, `afterClose` is undefined according to `timber.js`. What file did you put `afterClose` in?

**Comment by cshold** [comment]
I just updated your JS file from `  'onDrawerClose': afterClose` to `  'onDrawerClose': timber.afterClose`, and the afterClose function to:
```
timber.afterClose = function() {
  alert('closed');
};
```

Seems to work as expected now

**Comment by spring-91** [comment]
Ah perfect thank you, I tried that way originally but got confused, many thanks for helping with this. You're awesome!

**Comment by cshold** [comment]
My pleasure!
