### ISSUE TITLE
grid broken on Safari iOS8

### ISSUE THREAD

**Issue by gina3five** [Shopify/Timber#420]
:nth-child appears to not work on Safari on iOS8, which totally breaks the self-clearing grid items.

**Comment by cshold** [comment]
This is a [known bug](http://stackoverflow.com/questions/26032513/ios8-safari-after-a-pushstate-the-nth-child-selectors-not-works) and only happens occasionally. Still have to test if the nth-of-type is a worthwhile fix.

**Comment by gina3five** [comment]
Yep, seems to work for me.

**Comment by cshold** [comment]
Going to close this as it's a pretty rare case of actually causing layout issues for your users. For those that run into this, check out the link I posted above for a fix in your build.
