### ISSUE TITLE
Slider or Carousel

### ISSUE THREAD

**Issue by dpanfili** [Shopify/Timber#424]
Any plans in implementing a default slider or carousel into this framework? I've been trying to find a solution to adding a slider with backend fieldsets to this framework but not having any luck.

**Comment by thisislawatts** [comment]
Hey @dpanfili,

I tend to only add homepage slideshows to my templates, which are then managed via [shopify's theme customize](https://docs.shopify.com/manual/your-website/themes/customize). 
See here for a sample index.liquid/settings_schema.json
https://gist.github.com/thisislawatts/8859e2fa18ed087a0acb

What resources have you been trying so far?

**Comment by Cam** [comment]
@dpanfili I usually just use Slick by @kenwheeler https://github.com/kenwheeler/slick

Slick mixed with that markup for settings and html from @dpanfili and you should have a working solution pretty quickly.

If you are interested, I am working on a suite of complementary assets designed to work specifically with Timber. I'll be including a slider in those resources soon. I'm calling it "[Twigs for Timber](https://github.com/Elkfox/Twigs-for-Timber/)". Hilarious, I know :/

**Comment by cshold** [comment]
:+1: to "Twigs for Timber" @Cam - love it.

Agreed that Slick is a fantastic resource — we actually used it on our latest theme, [Brooklyn](https://themes.shopify.com/themes/brooklyn/styles/brooklyn) (with some customizations). There are no plans to add modules like sliders in at the moment.

**Comment by kenwheeler** [comment]
If you guys need any features or support on my side for a future Slick integration just let me know

**Comment by Cam** [comment]
@kenwheeler If you could add an image zoom feature, you would be making life super easy for a whole load of us Shopify devs :dancers: ...not sure that fits with the intentions of Slick though.

@cshold Thanks Carson! It's a slightly silly name, but it just seemed to fit so nicely :)

**Comment by gagankhokhar** [comment]
thankyou

**Comment by samueldiggins** [comment]
I'm trying to replace the default Timber product gallery with Slick, and already have the thumbnail/main image slider syncing working. However,  I'm struggling to update the main image when a new variant is selected in the option dropdown. This seems to be handled within timber.js.liquid:

`
if (variant.featured_image) {
var newImg = variant.featured_image,
el = $productImage[0];
Shopify.Image.switchImage(newImg, el, timber.switchImage);
}
`

...but I can't seem to trigger the image to update within Slick. Any ideas, @kenwheeler?
