### ISSUE TITLE
Change the transition applied to Ajax Cart Product Row when a product is removed?

### ISSUE THREAD

**Issue by spring-91** [Shopify/Timber#432]
Hi,

I'd like to change the animation/transition thats currently being applied to the product row in the ajax cart when the product is removed from the ajax cart.

I'd like it to just fade the product row out and then slide the remaining product rows up but I'm having some trouble locating the code thats currently controlling what happens.

Am I right in thinking the `.ajaxcart__product { &.is-removed {...} }` is whats controlling the transition? Is there anything anywhere else?

Any help would be appreciated, many thanks in advance!

**Comment by cshold** [comment]
Yes, that's all that's controlling the animation. If you want a fade and then a slide, I'd suggest removing the styles associated with `is-removed` in the CSS and do it only in JS. It's possible to do with CSS keyframe animations as well, but can be tricky to get the timing right.

**Comment by spring-91** [comment]
Great, thanks for confirming that for me. I'll have a go with what you have suggested.

Thanks again!
