### ISSUE TITLE
'form.posted_successfully?' Doesn't work for address forms

### ISSUE THREAD

**Issue by admanami** [Shopify/Timber#433]
According to these docs:
https://docs.shopify.com/themes/liquid-documentation/objects/form#form-posted_successfully

form.posted_successfully? should work within the {% form %} tag.

However this does not work:

{% form 'customer_address', address %}

{% if form.posted_successfully? %}
Success
{% else %}
{{ form.errors | default_errors }}
{% endif %}

{% endform %}

—————— And nor does this: ——————

{% form 'customer_address', address %}

{% if form.posted_successfully? %}
Success
{% else %}
{{ form.errors | default_errors }}
{% endif %}

{% endform %}

------------------------
Neither the add, edit or delete functions seem to be able to return a success/failure which can be output on the front end.

**Comment by Cam** [comment]
Check you don't have the form.posted_successfully tag in your header too. If there are 2, it won't work.

**Comment by cshold** [comment]
@fredryk any ideas on this?

**Comment by fredryk** [comment]
@Thibaut knows most about this issue. I'm looping him in for some insight.

**Comment by admanami** [comment]
@Cam No, there are no other instances. Ty.

**Comment by Thibaut** [comment]
This issue is being tracked inside Shopify. It's not a straightforward fix because the `address` object passed to the `form` comes from a loop over the customer's addresses, which might be paginated over in different ways. We haven't given up on the bug though.

**Comment by cshold** [comment]
Closing as this isn't Timber-related
