### ISSUE TITLE
Multi-level dropdown nav-bar?

### ISSUE THREAD

**Issue by jared83** [Shopify/Timber#434]
Does the timber nav bar support multi-level dropdowns on both - desktop and mobile versions?
Something like this:
http://cdn.tutsplus.com/webdesign/uploads/legacy/tuts/378_tessa/tessa-lt-dropdowns-21c7868/index.html
I tried to simply add nested ul, but that didn't work.
Has anyone tackled this problem?
Thank you for your time.
Love your work.
Jared

**Comment by cshold** [comment]
Yes, Timber currently ships with a single level dropdown on desktop, and a hidden drawer nav with collapsable dropdowns on mobile. Check out the demo at https://timber-demo.myshopify.com/
