### ISSUE TITLE
Changing Ajax Cart Quantity -/+ to a <select> drop-down?

### ISSUE THREAD

**Issue by spring-91** [Shopify/Timber#437]
Hi,

Not sure if this is something you can help me with?

I've successfully managed to change the Quantity -/+ into a select dropdown using the following code on the Cart Page. However I'm struggling to adapt it to work in the Ajax Cart. Am I on the right lines or completely missing something? Is this something thats possible in the Ajax Cart?

Code used and working in Cart Template:

    <select id="updates_{{ item.id }}" name="updates[]"> 
       {% for i in (1..10) %} {% assign q = i %}
           <option value="{{ q }}"{% if item.quantity == q %} selected{% endif %}>{{ i }}</option>
       {% endfor %}
     </select>

Code I'm trying to adapt for Ajax Cart Snippet:

    <select class="ajaxcart__qty-num"> 
        {% for i in (1..10) %} {% assign q = i %}
             <option value="{{ q }}"{% if itemQty == q %} selected{% endif %}>{{ i }}</option>
        {% endfor %}
    </select>

Any help would be most appreciated!

Thanks in advance.

**Comment by cshold** [comment]
On [line 326 of ajax-cart.js.liquid](https://github.com/Shopify/Timber/blob/master/assets/ajax-cart.js.liquid#L326) there is a listener for each click on the plus/minus button. This is where you'll need to update to listen for a `change` on the select element. Something like `$body.on('change', '.ajaxcart__qty-num', function() {...}`.

Make sure the `select` has a `data-line` attribute so the cart knows which product to update. You can remove the references to `$qtySelector` and instead use the value of the selected option. It'll take some custom work, so if you need some extended help I'd suggest reaching out in our [design forums](https://ecommerce.shopify.com/c/ecommerce-design).

**Comment by akshayshivpuri** [comment]
Looking for the same solution. Were you able to implement the solution spring-91?
