### ISSUE TITLE
Duplicate IDs

### ISSUE THREAD

**Issue by suture** [Shopify/Timber#439]
Just running the W3C validator on the demo store homepage and it looks like it has a few problems with duplicate IDs. 

Line 261, Column 68: Duplicate ID customer_login_link.
Line 202, Column 62: The first occurrence of ID customer_login_link was here.
Line 263, Column 76: Duplicate ID customer_register_link.
Line 206, Column 68: The first occurrence of ID customer_register_link was here.

It looks like it also effects other Timber based themes such as Supply.
re: https://ecommerce.shopify.com/c/ecommerce-design/t/supply-theme-fails-w3-validation-test-269326#comment-269375

**Comment by zacwasielewski** [comment]
This isn't really Timber's fault. Shopify adds an `id` to the link generated by the [customer_login_link](https://docs.shopify.com/themes/liquid-documentation/filters/url-filters#customer_login_link) filter:

    # Input:
    {{ 'Log in' | customer_login_link }}
    
    # Output:
    <a href="/account/login" id="customer_login_link">Log in</a>

On every page, Timber creates two navigation menus (desktop/mobile), each containing a login link. Deleting one of those menus is the only way to solve the problem you reported.

The real solution would be for Shopify to change that `id` to a `class`:

    <a href="/account/login" class="customer_login_link">Log in</a>

**Comment by suture** [comment]
One option might be to code it without the filter.

**Comment by zacwasielewski** [comment]
That would work – but if Shopify changes their login link URLs, then all Timber-based themes will break.

For some themes, it may be worth hardcoding login links in order to please the validator. That's a tradeoff the theme designer should consider. But Timber should "do the right thing" by default and play by Shopify's rules, even if they're a bit broken.

**Comment by suture** [comment]
Yes good point.

Some nav systems use the same unordered list for both desktop and mobile, which might avoid the problem. But it would be major pain to change it now. 

I will close on that note.
