### ISSUE TITLE
When a drawer is opened 'position:fixed' elements outside the drawer jump?

### ISSUE THREAD

**Issue by spring-91** [Shopify/Timber#440]
Hi there,

I'm having an issue with my theme. I have some elements (e.g. Logo / Register/Login links) that are positioned as fixed. When any drawers are opened they jump up as though they have returned to position:relative.

Any idea why this might be? Is there something in the javascript that is telling the `#PageContainer` to change when the drawer is open?

This could be an error on my part but at this point I'm not too sure. Here is a [link](http://www.hatch-inc-tester-store.myshopify.com) to my demo page to see whats happening.

If this is something you could help with it would be most appreciated. Many thanks in advance.

**Comment by cshold** [comment]
`.js-drawer-open-right .is-moved-by-drawer`'s styles, specifically the `translateX` look to be conflicting with your fixed elements. You've done a lot of custom work so I'm going to close this, not being related to the framework itself.

You can use classes `js-drawer-open-right` and `js-drawer-open-left` to adjust the styles on the fixed elements. Fair warning, having fixed elements react with a drawer layout like that will be very tricky.
