### ISSUE TITLE
Custom Modernizr JS icon conflict

### ISSUE THREAD

**Issue by Cam** [Shopify/Timber#444]
When using custom versions of Modernizr, the Timber icon font no longer works. This is with the current version of Modernizr, with the @fontface component included.

**Comment by Cam** [comment]
This seems to happen when adding "CSS Animations" to the Modernizr build

**Comment by cshold** [comment]
Change instances of `supports-fontface` to what ever your version of modernizer is adding instead. ([source](https://github.com/Shopify/Timber/blob/master/assets/timber.scss.liquid#L1621)). I believe there are just three.

**Comment by Cam** [comment]
Thanks @cshold. We did actually use the same version with the "supports" prefix and everything. I'll play around with it though, and see if I can find anything else. But I am starting to suspect this is a Modernizr issue, not a Timber issue.

**Comment by cshold** [comment]
Alright. I'll close this for now, but I'd love to hear what's causing the issue.

**Comment by Cam** [comment]
Sounds good. I'll be sure to update you when I have more info.
