### ISSUE TITLE
Ajax cart could utilise the jQuery API options better

### ISSUE THREAD

**Issue by Cam** [Shopify/Timber#448]
I'm sure this isn't too difficult for a JS smartypants to achieve. But, I think it would be great to add some extra functionality to the ajax cart js to accommodate scenarios that aren't 100% vanilla.

I would think some things like "remove all items of variant" and "empty cart" could be very useful.

Better still, the Timber JS itself could accommodate the lot, and offer some simple alternative configurations that make full use of the Ajax API, including the options for the Ajax cart (a few options for this are currently in multiple places, including the bottom of the theme.liquid).

Or maybe not? :P

**Comment by cshold** [comment]
I'd recommend checking out https://cartjs.org for more extensive cart API usage. It's not something we're planning to add to Timber.
