### ISSUE TITLE
Hover states and links whilst drawer is open.

### ISSUE THREAD

**Issue by spring-91** [Shopify/Timber#449]
When the drawer is open, any elements with a hover state e.g links still act as if they are active when you hover on them (change of colour etc). Is it possible to disable these on hovers whilst the drawer is open? How would I achieve this? 

Just wondered if this would make better sense?

**Comment by cshold** [comment]
You should definitely tailor this to your theme, rather than rely on Timber's defaults. You can change that here - https://github.com/Shopify/Timber/blob/master/assets/timber.scss.liquid#L2067

**Comment by spring-91** [comment]
Sorry I've realised I didn't make it clear in my question. I meant any links **outside** of the drawer still look as though you can click on them because they change colour on hover etc. when the drawer is open. 

Would I still need to edit the code you suggested or is that specifically for links within the drawer? Also apologies for the delay in reply I missed the email.

Thanks for your help.

**Comment by cshold** [comment]
The code I mentioned is specifically for inside the drawer. If you want to disable hovers on links outside the drawer, I'd suggest creating a transparent div that covers the entire `#PageContainer` div. It would need `display: none` by default, and `display: block` when `.js-drawer-open` is on the `html` tag.

**Comment by spring-91** [comment]
Awesome, i'll implement that now. Thanks Carson!
