### ISSUE TITLE
Search Results on products that contain variants

### ISSUE THREAD

**Issue by cmanspeaker** [Shopify/Timber#450]
Receiving the following error on products that contain a variant in the search results page

translation missing: en.products.general.from_text_html

{% if item.price_varies %}
{% assign price = item.price | money %}
<span itemprop="price">{{ 'products.general.from_text_html' | t: price: price }}</span>
{% else %}
<span itemprop="price">{{ item.price | money }}</span>
{% endif %}

Lines 101 - 107

I believe this situation also exists for on sale items and is repeated in the grid search results.

I've changed the line in question from:
<span itemprop="price">{{ 'products.general.from_text_html' | t: price: price }}</span>
to:

<span itemprop="price">{{ 'products.general.from' | t }} {{ item.price | money }}</span>

which resolves the issue so not sure if this is a bug or a setting that may be off on my side.

**Comment by cshold** [comment]
Do you see `from_text_html` in `locales/en.default.json`? It should be nested under "products" and "general". Here's [the source](https://github.com/Shopify/Timber/blob/master/locales/en.default.json#L266)

**Comment by cmanspeaker** [comment]
Ah gotcha, that explains it. Yeah I need to make sure I've got the latest version of this file as my copy only has three items under general. Thank you for your help.
