### ISSUE TITLE
Push state on variant change not working by default

### ISSUE THREAD

**Issue by wardpenney** [Shopify/Timber#458]
I am trying to figure it out right now, but on a vanilla install of Timber theme:

Steps:

1. Make a product with a couple variants and with two options (size and color)
* View the product and change a variant selector

Actual Result:

* Url does not change

Expected Result:

* Url *does* change to the selected variant (so users can share it)

Notes:

* On line 162 of `product.liquid`, the `selectCallback` is function is being passed a null variant.
* It is hard to switch out the main image without that variant populated

**Comment by wardpenney** [comment]
Thanks for Timber, btw! I've used it on a couple projects in the last year, and this bug seems new to me.

**Comment by cshold** [comment]
Hey, I just updated the demo shop with what's in `master` and the URL changes as expected. Here's a demo - https://timber-demo.myshopify.com/products/ricky-straight-super-t-mens-jean?variant=780884073

Do you have a shop up that I can take a look at?

**Comment by wardpenney** [comment]
@cshold It looks like it works for me as well with [my test shop](http://timber-test-9.myshopify.com/products/minpin).

I will try to figure out what's going on with my client's shop. When I do a Timber theme, with their product data, the issue manifests.

Thanks for looking, and I'll post back when I figure it out.

**Comment by cshold** [comment]
If you keep running into issues, reach out to themesupport [AT] shopify.com and they should be able to point you in the right direction. I'll close this for now but feel free to open it back up if you see fit.

**Comment by wardpenney** [comment]
@cshold It turns out I was choosing a variant that did not exist, and not handling the `null` state for that. Thanks for your help!
