### ISSUE TITLE
Add {{image_size}} variable to product-grid-item snippet

### ISSUE THREAD

**Issue by jholl** [Shopify/Timber#463]
looking at the `product-grid-item.liquid` snippet the image size is hardcoded 'large'.  Could we add a variable to that snippet which would allow us to pass in  `image_size` on the fly when calling the snippet (i.e. setting different size for related products loop vs collection loop).  I can create a PR if you're up for it; which branch -- it'll be non-breaking bc we'll check for the variable or set default like with `grid_item_width`?

this also then fits really nicely with the [related products tut](https://docs.shopify.com/support/your-store/products/can-i-recommend-related-products#finding-a-relevant-colleciton) in docs

**Comment by cshold** [comment]
That sounds like a case-by-case need so not needed in the framework itself. Open to reasons it would be valuable to a wider audience though.

**Comment by jholl** [comment]
yes, I thought about this more.

The difference of rendering a '_large' or _'compact' image on a six item grid appears irrelevant with responsive images (I haven't done a test of load speed, but probably also insignificant); so there's not much argument for varying image size if the only benefit can already be achieved with `grid_item_width`

So far as I'm concerned now, we can close any time.
