### ISSUE TITLE
Sub Sub Menus

### ISSUE THREAD

**Issue by suture** [Shopify/Timber#464]
It seems the navigation doesn't support nested sub-menus within sub-menus. Would it be possible to add support for this?

**Comment by Cam** [comment]
I really really don't think this should be a thing. Sub-sub menus generally aren't any good. If you want something made that could plug in to Timber that has scope for a third tier, You could sign up at http://twigs.club and harass me to make one ;)

**Comment by suture** [comment]
I personally don't like them either. 

It seems that they aren't supported in any of the free themes, but they are supported in some of the premium themes that I've tested.

I'm sure I can work out how to do it myself. Just thinking it would be good if there was a vetted solution.

**Comment by suture** [comment]
Thanks for the Twigs link. The testimonial carousel looks good. But the licensing is limiting isn't it?

**Comment by Cam** [comment]
@suture No, it is GNU/GPL. Where did you see otherwise? I'm happy to update any licensing if I had missed something :)

**Comment by suture** [comment]
@Cam maybe my mistake. Does GNU/GPL allow distribution in commercial themes? Does the commercial theme then fall under the same license? Sorry to push this issue of subject :)

**Comment by Cam** [comment]
@suture All good! Though this should be raised not the Twigs Github, so as not to pollute the Timber issues. The licenses specify that you can use the assets freely in commercially distributed themes. You just have to leave the appropriate licences and credits for those components in tact (within the code only).

**Comment by cshold** [comment]
Agreed, no need to sub-sub-menus in a framework. When done, they have to be very specific to the theme.
