### ISSUE TITLE
Twitter card descriptions

### ISSUE THREAD

**Issue by paulmason** [Shopify/Timber#468]
Just noticed a bit of an inconsistency https://github.com/Shopify/Timber/blob/master/snippets/social-meta-tags.liquid

Line 46:
```
<meta property="og:description" content="{{ page_description | escape }}”>
```

Line 71:
```
<meta name="twitter:description" content="{{ product.description | strip_html | truncatewords: 140, '' | escape }}”>
```
Line 77:
```
<meta name="twitter:description" content="{{ article.excerpt_or_content | strip_html | truncatewords: 140, '' | escape }}”>
```

The code on line 46 is a bit more versatile. I think line 71, & 77 would be better written as:
```
<meta name="twitter:description" content="{{ page_description | escape }}”>
```

The page description is used for the meta description and automatically inherits from the product.description and article.excerpt_or_content. Using the page description gives the user that extra step of control. Sometimes the product descriptions will have html that needs to be rephrased to make sense in plain text.

**Comment by chrisbo** [comment]
Noticed the same issue with the New Standard template yesterday. Raised it with support about 24-hours ago - which was initially like talking to a brick wall. Eventually, the so called guru said he would elevate it. No reply yet though.

**Comment by cshold** [comment]
`page_description` definitely makes sense. A blog article, for example, currently looks like this:

og:description
```<meta name="og:description" content="What's in this demo Check out the Timber documentation to learn more about using this framework in your own projects. This demo shop has a few things included i">```

twitter:description
```
<meta name="twitter:description" content="What's in this demo
Check out the Timber documentation to learn more about using this framework in your own projects.
This demo shop has a few things included in it:

A few demo products
An ajax cart enabled
Customer accounts enabled
Contact page
Custom logo (via theme settings)

Where's the style?
Timber has very little style so you can use your CSS chops to create a sweet custom shop. That means you don't have to remove a lot of code to get to a good starting place.

What does a Timber look like blank?
Things included in this demo are not necessarily enabled by default on brand new Shopify stores. By default, you'll have no products, accounts disabled, no logo, no contact page, among other features disabled.
Check out Timber installed on a brand new store">
```

Want to open a PR with the update @paulmason? I'd suggest adding the `trancatewords` filter though.

**Comment by paulmason** [comment]
Thanks @cshold, I've created that pull request https://github.com/Shopify/Timber/pull/491
