### ISSUE TITLE
New Feature Request

### ISSUE THREAD

**Issue by Shine18** [Shopify/Timber#470]
Please add the support of adding more drawers through javascript in your theme. It'll be very helpful to us developers.

**Comment by cshold** [comment]
You can add as many as you'd like now, though only left/right ones are set up. Duplicate the existing menu or cart drawer markup and then initialize a new drawer with [this syntax](https://github.com/Shopify/Timber/blob/master/assets/timber.js.liquid#L185).

Note that there currently is a bug if you try and close a drawer (via the close button) when multiple ones are open.

**Comment by Shine18** [comment]
hmmmm, thanks for telling me

On Sun, Sep 20, 2015 at 9:53 PM, Carson Shold <notifications@github.com>
wrote:

> Closed #470 <https://github.com/Shopify/Timber/issues/470>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Shopify/Timber/issues/470#event-414214556>.
>



-- 

Great Blessings and Lovings from me.
Kind Regards,

Aakash Ahmed
