### ISSUE TITLE
Breaking Out Of Wrapper On Index

### ISSUE THREAD

**Issue by marshall993** [Shopify/Timber#477]
Hey, 

Not so much an issue just a question (do you have a support contact?) anyways I was wondering how to create a full width section that breaks out of the wrapper on the index.liquid file similar to Bootstraps container-fluid.

Thanks,
Great Base Theme.

**Comment by Cam** [comment]
You've answered your own question :D Literally break the grid outside of the wrapper! If the grid isn't in the wrapper, it will be full width.

**Comment by marshall993** [comment]
Hi Cam,

Thanks for the response please let me clarify the index content is held by this snippet:

<main class="wrapper main-content" role="main">
 {{ content_for_layout }}
</main>

But everything in the index file is held between the wrapper based off the theme.liquid file so I cannot break out of the container seeing as the file is inside of this.

**Comment by cshold** [comment]
Remove the `wrapper` class from `main-content` and add it (`<div class="wrapper">) when needed as a new wrapper div on a per-template basis.

**Comment by marshall993** [comment]
Hi Cshold,

Jesus didn't even think of that thanks a million!!

-Scott
