### ISSUE TITLE
Thumbnails open out-of-page (Chrome, windows)

### ISSUE THREAD

**Issue by ukk000** [Shopify/Timber#478]
On the product page, when clicking a secondary photo's thumbnail, the new photo is loaded into the main photo's place but immediately after you get redirected to view the file itself. Happens every 3rd or so time.

Tested on Chrome 46.0.2490.80 on windows using the timber demo store (https://timber-demo.myshopify.com/products/rattle-indigo-mens-tee)

**Comment by cshold** [comment]
Only assumption is that the JS hasn't initialized yet for some reason and you're following the default `href` of those thumbnails. Did you see any JS errors?

**Comment by ukk000** [comment]
There was some lnkr.js notification that flashed quickly before going to the href, I'll check what it was.

**Comment by cshold** [comment]
lnkr.js isn't a part of Timber so not sure where you saw it. Closing the issue, but feel free to reopen if you see fit.
