### ISSUE TITLE
Amazon icon not displaying

### ISSUE THREAD

**Issue by chanhman** [Shopify/Timber#485]
Is Timber updated to include the amazon payment icon? I see it on your documentation but I can't seem to get it to display. I am currently using Shopify's Brooklyn theme and it's not displaying. I tried updating the font icon files with the files from your repo, but it still doesn't display.

<img width="1280" alt="screen shot 2015-11-12 at 4 16 57 pm" src="https://cloud.githubusercontent.com/assets/9286750/11134310/d887bd46-8958-11e5-82ac-fd85b223ce25.png">

**Comment by cshold** [comment]
I wouldn't suggest taking Timber's icons directly and putting them in Brooklyn as we customized a number of the icons for that theme. Here are some steps to update Brooklyn's icon set:

1. Grab `icons.json` from the assets folder of Brooklyn and upload it to https://icomoon.io/app
2. Upload an SVG for the Amazon Payments. [Here is the one we use](https://www.dropbox.com/s/ki9569v0awa2i4w/icon-amazon_payments.svg?dl=0). Make sure the icon is named `amazon_payments` before exporting.
3. Export the fonts (lower right corner of the app). You will get a zip file.
4. Make sure the files are named `icons.extension`, move them to your assets folder
5. Rename `selection.json` from the zip to `icons.json` so you have the most up to date versions in case you need to make other changes as well. Place that in your assets folder.
6. Take the css font mapping from `styles.css` in the zip and replace what exists in `assets/timber.scss.liquid`. Look for the "Icon Mapping" comment in timber.scss.liquid for where to place the updated code.
