### ISSUE TITLE
Breaking up theme.liquid into more manageable snippets

### ISSUE THREAD

**Issue by lukeclifton** [Shopify/Timber#488]
Hi Guys. Firstly thanks for all your hard work on Timber.

Sorry this has already been asked / addressed but....

Is there a reason that theme.liquid is not broken up in to more managable snippets?
The template is rather huge with lots going on understandably but its hard to navigate.

Would be nice if key components like header, nav and footer were broken up into seperate snippets at least?

Thoughts?

**Comment by cshold** [comment]
We have discussed it before and go back and forth on it. In short, we're not going to do it.

For some context, we decided to stay away from it for the sake of merchants that find themselves in their admin trying to adjust a little bit of code. A lot of our docs say "go into your `layout/theme.liquid` file and find your footer, then ______" — or something along those lines. Asking merchants who are potentially uncomfortable in code to begin with to start hopping between snippet files can make their task at hand seem even more daunting.

The themes we build at Shopify are free and used by a lot of merchants so this is a big factor for us. If you're developing something for the theme store we'd suggest sticking to the same approach.

All that said, if you want to split them up yourself you absolutely can. It's very quick for a developer to pull elements they want out of `theme.liquid` and into snippets so we'll leave the onus on them to do that.

**Comment by thisislawatts** [comment]
Too quick for me @cshold, I was looking for the original issue where this was being discussed. For reference, gere's one of the commits where footer.liquid was merged back into theme.liquid
https://github.com/Shopify/Timber/commit/d2bd26d318f8096cc8a2ba4d512f02bc7ea0052d

**Comment by lukeclifton** [comment]
OK thanks for the explanation!

I would argue that it would actually be easier for non savy coders to find which part of code their looking for by having snippets. I've seen themes hacked by non savvy coders and because theres just one big template they start putting bits of code in the wrong places and it all gets very messy. I think best practice should be encourged by the inital theme build.

But as you said, developers can always break up theme.liquid if they desire.

Good to know your reasoning though.

Thanks!
