### ISSUE TITLE
Javascript error in addresses page

### ISSUE THREAD

**Issue by rubenbristian** [Shopify/Timber#489]
Hi

There's a big js error in the addresses.liquid file when address pagination kicks in. I've reported it to Shopify last year, but it seems that it's still here..

When you are on page 2 of addresses it is impossible to edit or add new addresses, because there's a js error caused by the fact that the handlers aren't setup with pagination in mind. 

The solution is simple, you just need to add pagination in the js part, when calling the Shopify js functions.

```
{% paginate customer.addresses by 5 %}
  {% for address in customer.addresses %}
    new Shopify.CountryProvinceSelector('AddressCountry_{{ address.id }}', 'AddressProvince_{{ address.id }}', {
      hideElement: 'AddressProvinceContainer_{{ address.id }}'}
    );
  {% endfor %}
{% endpaginate %}
```

**Comment by cshold** [comment]
Want to open up a PR with the fix?

**Comment by rubenbristian** [comment]
Sure, i can do that.

**Comment by suture** [comment]
Thanks for this

**Comment by cshold** [comment]
Can't find the PR to link to, but the [code is in master](https://github.com/Shopify/Timber/blob/a3ddf4c3351812d693dcf4b2ff76c344c8d45237/templates/customers/addresses.liquid#L208-L212) so closing this.

**Comment by cshold** [comment]
I lied - it's missing the `pagination` tags. @rubenbristian did you ever open a PR that I missed?
