### ISSUE TITLE
Links stop working in the shop section a few seconds after the page loads

### ISSUE THREAD

**Issue by woodjaclyn** [Shopify/Timber#500]
I've had some customers say that they can't click on links on the home page or shop page of my website (other pages of the website seems to be fine). Links will work if someone clicks a link immediately after the site loads, however if they wait a few seconds before attempting to click a link, the cursor 'hand' will turn into the standard cursor 'pointer' and the links seem to be disabled - they are no longer clickable. Is there a way to fix this? I've never seen this issue before, and can't find any help pages anywhere to give me answers as to what to do with this issue.

This is where the links stop working:
http://freenotecloth.com/collections/shop

**Comment by suture** [comment]
I think it's because of the full screen modal. 

![screen shot 2016-01-28 at 8 26 59 am](https://cloud.githubusercontent.com/assets/90376/12632136/0c65c794-c599-11e5-8280-d8ec8c6c629c.png)
