### ISSUE TITLE
Feature Request: Flexbox Grid System

### ISSUE THREAD

**Issue by gina3five** [Shopify/Timber#501]
Would love to see this theme framework implement a flexbox based grid system.

Just a friendly nudge to push the bar and lead the way. :)

**Comment by cshold** [comment]
We still fully support IE9 and a few older Android devices for Shopify-built themes so can't make that jump just yet on something so instrumental as the grid.

We absolutely value and leverage flexbox when we can on a smaller scale when lack of support is easier to mitigate with sensible fallbacks.
