### ISSUE TITLE
Erratic Scrolling on Mobile for Cart Overflow

### ISSUE THREAD

**Issue by softlimit** [Shopify/Timber#505]
I'm having an issue where a long list of items in ajax cart doesn't always want to scroll on touch-screen / mobile devices (iOS, iPhone 6 specifically). When this happens, the background page scrolls instead and items in the cart remain fixed. The issue seems to happen on Timber Demo as well as on my build... but neither is doing so consistently – sometimes all works perfectly, sometimes it doesn't. I know there is [this previous issue](https://github.com/Shopify/Timber/issues/457) from July 2015, but in our case, the behaviour is definitely detracting from the user experience as users can't scroll to the bottom of the cart. It's a difficult issue to pinpoint but maybe others have seen the issue?

**Comment by cshold** [comment]
@softlimit Can you test out the demo shop again and see if it's still happening? Hopefully iOS fixed the rendering/layout issue - I know Safari had a number of issues when iOS 8 launched but fixed them quite quickly. A screencast of the issue would be really helpful as well.

**Comment by softlimit** [comment]
Thanks, @cshold. I can't seem to replicate on demo shop anymore. We adjusted our cart to move the Check Out button to the top to help with the issue... though it still seems to happen occasionally. It definitely has something to do with WHERE the tap to scroll is initiated. Let me see if I can get a screencast together... ok to send that to your email?

**Comment by cshold** [comment]
A link or embed here would be ideal if you can do that, so others can see it in action as well. Cheers.

**Comment by lukeclifton** [comment]
We were experiencing a similar issue to what @softlimit has mentioned. The following solution seems to have worked for us:

Add a child  `.drawer-content` div directly inside the `.drawer` parent div.

Give the child `.drawer-content` div the following style: 

```
  .drawer-content {
    height: 100%;
    overflow-y: scroll;
    overflow-x: hidden;
  }
```

And also add `position: fixed;` to the `.drawer` class

This solution ensures that the drawer always scrolls vertically and the body does not move while the drawer open.

**Comment by softlimit** [comment]
Thanks, @lukeclifton! That seems to do the trick!
