### ISSUE TITLE
Cart error

### ISSUE THREAD

**Issue by Tardis1234** [Shopify/Timber#512]
In the cart drawer, if the user clicks the quantity ticket _very quickly_ more times than the quantity available for that item you get the alert "cannot update empty cart(bad_request):null".

I was able to replicate this bug easily in the Boundless theme.

![screen shot 2016-02-22 at 6 44 06 pm](https://cloud.githubusercontent.com/assets/8463736/13236817/ef43a072-d994-11e5-8bd8-9e70ccfb32c5.png)

**Comment by cshold** [comment]
Boundless wasn't built on Timber. If you're able to recreate this on a fresh install of Timber feel free to reopen the issue.

For what it's worth, that issue has since been fixed on Boundless, so thanks for noting it.
