### ISSUE TITLE
Multiple Drawers Left

### ISSUE THREAD

**Issue by srmurphy127** [Shopify/Timber#523]
I need to setup a left drawer for collection tag filtering on mobile. The cart already uses the left drawer call what is easiest way to create second drawer? I only see options to call a single left or right drawer in the docs.

**Comment by cshold** [comment]
The `timber.LeftDrawer` and `timber.RightDrawer` names are arbitrary, so you can name a new one anything you'd like. The only important thing is the ID on the drawer (see [the left nav drawer as an example](https://github.com/Shopify/Timber/blob/master/layout/theme.liquid#L54)), so make sure that one is unique for your new one. Then set `left` or `right` for the second parameter to make the drawer start on the appropriate side.

**Comment by vosters** [comment]
I'm having the same issue. I'm using a different id, yet the other drawer still opens and lays on top of the new drawer.
