### ISSUE TITLE
About javascript in ajax cart - Cant add another script

### ISSUE THREAD

**Issue by chrbmol** [Shopify/Timber#528]
`I` postet a question yesterday about adding another javascript to my ajax cart. 

i was told to look here: http://shopify.github.io/Timber/#ajax-cart

But that wont help me. 

Right now this is what i have in my theme file, just as a test: 
`___________`
```
<script>
  jQuery(function($) {
    ajaxifyShopify.init({
      method: '{{ settings.ajax_cart_method }}',
      wrapperClass: 'wrapper',
      formSelector: '#addToCartForm',
      addToCartSelector: '#addToCart',
      cartCountSelector: '.cart-count',
      toggleCartButton: '.cart-toggle',
      useCartTemplate: true,
      btnClass: 'btn',
      moneyFormat: {{ shop.money_format | json }},
      disableAjaxCart: false,
      enableQtySelectors: true
    });
  });
     jQuery('body').on('ajaxCart.afterCartLoad', function(evt, cart) {
 
consol.log("Hej Jacob");
 });
 
  </script>
```

______

But the Hej Jacob message wont show. 

Why is it not working??

**Comment by cshold** [comment]
`ajaxifyShopify` should be `ajaxCart`. The rest of the code looks good. What's your shop URL?

**Comment by chrbmol** [comment]
Hey! 

It is billig-fitnessdk.myshopify.com

I have tried that, but still not working

**Comment by cshold** [comment]
Ah, you're working off of Supply which uses an older version of Timber.

In `ajaxify.js.liquid` find the `buildCart` method. At the very bottom (below `cartInit = true`), add `$body.trigger('ajaxifyShopify.afterCartLoad', cart);`

That way the event listener from your code snippet above will work, but use `ajaxifyShopify` instead of the `ajaxCart` I said earlier.

**Comment by chrbmol** [comment]
I have tried it out now - It is not working, and only breaking the cart? 


Mvh

Christian Møller fra
www.billig-fitness.dk <http://www.billig-fitness.dk/>

Tlf: 42 83 10 33 
Mail: cm@billig-fitness.dk <mailto:cm@billig-fitness.dk> 




> Den 19/04/2016 kl. 16.10 skrev Carson Shold <notifications@github.com>:
> 
> ajaxifyShopify

**Comment by cshold** [comment]
Didn't realized `useCartTemplate` was true. Move `$body.trigger('ajaxifyShopify.afterCartLoad', cart);` to after `cartTemplate(cart);` and before `return` (line 757).

Closing this as it's not an issue with the framework.
