### ISSUE TITLE
Demo store - Dummy content [Request]

### ISSUE THREAD

**Issue by terkelg** [Shopify/Timber#54]
I think it could be very useful for theme developers if the "dummy content" from the demo store was included with Timber or available for download. It's a time saver and good for testing themes.

**Comment by andrew-saint** [comment]
Any update on this? Shopify has been a pleasure to work with so far, but the lack of any decent dummy data for developers is disappointing.

**Comment by cshold** [comment]
The CSV linked to above is still the best way to get test products into your store. While we're experimenting with different ways to get more test data for devs/designers, it's a complex and ultimately slow process.
