### ISSUE TITLE
Imported new icons, but not working

### ISSUE THREAD

**Issue by jamalsoueidan** [Shopify/Timber#544]
Hello,

We have imported few extra icons using IcoMoon.

1. Imported old file
2. Added new icons
3. Generate Font
4. Added CSS new icons 

```
.icon-coin-euro:before { content: "\e93c"; }
.icon-credit-card:before { content: "\e93f"; }
.icon-envelop:before { content: "\e945"; }
.icon-truck:before { content: "\e9b0"; }
.icon-question:before { content: "\ea09"; }
.icon-mail2:before { content: "\ea84"; }
```

5. Used the icons on the page

`<span class="icon icon-credit-card"></span>`

The icons is not visible?

Are we doing something wrong?

**Comment by cshold** [comment]
Nope, those are the right steps. Make sure you also uploaded all the font files — there are four of them. The font names should be `icons.svg`, `icons.ttf`, `icons.woff`, and `icons.eot`. 

Are the other icons showing on the page?

**Comment by jamalsoueidan** [comment]
Yes, I uploaded all four files, and all other icons is working.

Link: www.hookahsale.com 
Password: hookahsale
