### ISSUE TITLE
Sticky fixed header not working

### ISSUE THREAD

**Issue by jehuty15** [Shopify/Timber#554]
I have installed this theme (un-edited) but I can't seem to get a fixed or sticky header to work.

I'm using this code in my css but the header doesn't stay fixed at the top.

.site-header {
  position: fixed;
  width: 100%;
  z-index: 900;
  top: 0;
  left: 0;
  right: 0;
  height: 60px;
}

I've tried this with the Launchpad-Star theme that comes with Shopify and it seems to work fine, but doesn't work with timber. 

any help would be much appreciated.

**Comment by amandeepsinghvirdi** [comment]
Disable these styles from #PageContainer's class ".is-moved-by-drawer":

is-moved-by-drawer {
    -webkit-transform: translateZ(0);
    will-change: transform;
   transition: all 0.4s cubic-bezier(0.46, 0.01, 0.32, 1);
}


And it should work fine.

**Comment by cshold** [comment]
Feel free to reopen if you need more feedback.
