### ISSUE TITLE
Add "Next and Prev" arrows to Product page thumbnails

### ISSUE THREAD

**Issue by ttiimmaacc** [Shopify/Timber#578]
Can I add "next and prev" arrows to the main Product image to slide through thumbnails as an extra functionality?

Visual..  :)

..... Image: < [] >
 Thumbs :   [] [] [] []

**Comment by cshold** [comment]
Yes you certainly can, though it's not a part of Timber by default. I would suggest [Slick slider](http://kenwheeler.github.io/slick/) for this type of functionality.

**Comment by ttiimmaacc** [comment]
Thankyou carson!
