### ISSUE TITLE
Possible to get a `checkout.liquid` starter file?

### ISSUE THREAD

**Issue by JamesCropcho** [Shopify/Timber#580]
Hello all,

Thanks much for Timber; it makes my life a little happier.

I'm building something for Shopify Plus, which allows not only a theme.liquid, but a checkout.liquid.

I see Timber doesn't have a checkout.liquid. Is there somewhere else I could look to find a "starter" version?

Thank You,
James

===
checkout.liquid: https://help.shopify.com/themes/development/layouts/checkout-liquid

**Comment by aalfson** [comment]
Yeah, this would definitely be a big time saver.

**Comment by JamesCropcho** [comment]
Hello Aaron ( @aalfson ),

I learned that even if a Development Store is upgraded to a Plus Store, which must be done manually by a Shopify employee, a Shopify employee must still further allow a custom `checkout.liquid`. I haven't found this documented publicly anywhere (until now).

When that's completed, a second layout option will appear in the 'new layout' dropdown, allowing the creation of the default `checkout.liquid` for further customization.
