### ISSUE TITLE
Adding notes function to embedded shopify cart

### ISSUE THREAD

**Issue by audilou88** [Shopify/Timber#584]
hi there, 

My shopify buy button produced the coded below, which I'm supposed to embed on my squarespace site. I've done that but it doesn't allow me to have my customer enter notes @ the cart page. Is there a way to add a text area parameter to this code, that will be accepted by shopify?

<div data-embed_type="product" data-shop="shbbleo2935.myshopify.com" data-product_name="Alabama Current Owner Title Searches" data-product_handle="alabama-title-searches" data-has_image="false" data-display_size="compact" data-redirect_to="cart" data-buy_button_text="Add to cart" data-buy_button_out_of_stock_text="Out of Stock" data-buy_button_product_unavailable_text="Unavailable" data-button_background_color="7db461" data-button_text_color="ffffff" data-product_modal="false" data-product_title_color="000000" data-next_page_button_text="Next page"></div>
<script type="text/javascript">
document.getElementById('ShopifyEmbedScript') || document.write('<script type="text/javascript" src="https://widgets.shopifyapps.com/assets/widgets/embed/client.js" id="ShopifyEmbedScript"><\/script>');
</script>
<noscript><a href="https://shbbleo2935.myshopify.com/cart/963384571:1" target="_blank">Buy Alabama Current Owner Title Searches</a></noscript>

**Comment by cshold** [comment]
This repo is specifically for the Timber framework, which doesn't sound like part of your issue. Please reach out to [Shopify Support](https://support.shopify.com/)
