### ISSUE TITLE
YouTube Video for Product Images

### ISSUE THREAD

**Issue by btschneider** [Shopify/Timber#595]
Is there a way to use YouTube video in the product image gallery? Here is an example of the effect:

https://www.beardbrand.com/collections/utility-balm/products/tree-ranger-utility-beard-balm

Thank you.

**Comment by cshold** [comment]
No, this is not baked into Timber. It looks like that shop uses the code for embedding an iframe as the thumbnail's `alt` text then uses JS to insert it. Definitely a cool effect for product pages
