### ISSUE TITLE
Cart Drawer New Standard Install

### ISSUE THREAD

**Issue by tomcollom** [Shopify/Timber#596]
Hello, 

I have a bespoke website that uses the 'new standard' theme and i have been trying to use impliment the timber ajax cart and drawer functionality. No matter what i try, the timber.scss file is not being read correctly and ultimately i cannot get this to work. 

Would anyone be willing to install this for me and if so how much would you charge ?

Thanks

**Comment by Cam** [comment]
Hi @tomcollom. You'll want to head over to the [experts directory](https://experts.shopify.com) or [job forums](https://ecommerce.shopify.com/c/shopify-job-board) for this question. The isn't a Timber related issue, so shouldn't be posted here ;)
