### ISSUE TITLE
No 'compare_at_price' for AjaxCart?

### ISSUE THREAD

**Issue by richgcook** [Shopify/Timber#598]
In the returned cart.js JSON there doesn't seem to be a 'compare_at_price' to be used.

**Comment by cshold** [comment]
I think you're looking for `original_price`

**Comment by richgcook** [comment]
Unfortunately not. `original price` is showing the new price... not the 'on sale' price.

<img width="751" alt="screen shot 2016-11-21 at 16 17 26 1" src="https://cloud.githubusercontent.com/assets/901289/20490515/26f62902-b006-11e6-8bea-99dfd34b1539.png">
<img width="373" alt="screen shot 2016-11-21 at 16 18 05" src="https://cloud.githubusercontent.com/assets/901289/20490514/26f57a7a-b006-11e6-9417-6c53454361a6.png">

**Comment by cshold** [comment]
Very strange. I'm looking into it and will get back to you when I know more.

**Comment by richgcook** [comment]
@cshold Thanks! I will keep looking too.

**Comment by cshold** [comment]
Looks like this is the expected behaviour. `compare_at_price` is not returned in the Liquid `line_item` (part of the `cart` object) either - [source](https://help.shopify.com/themes/liquid/objects/line_item).

What use case do you have to show off the compare at price in the cart?

**Comment by cshold** [comment]
That's the only use case I was thinking of too. It would certainly add confusion though when you add in [cart discounts](https://help.shopify.com/api/reference/discount). With that, you'd have your original price (`compare_at_price`), price of the product (`price`), and then the discounted price (`discounted_price`).

**Comment by richgcook** [comment]
Yeah that's a good point. But I see that as a separation between product and cart discount but I think it could still add confusion. Ah well... if it's not part of the API and therefore not possible then ah well but thanks for the replies and explanations.

**Comment by cshold** [comment]
Thanks for helping me learn more about cart discounts!
