### ISSUE TITLE
timber.scss.liquid 500 error

### ISSUE THREAD

**Issue by sdn90** [Shopify/Timber#60]
Not sure what happend but I just reuploaded timber.scss.liquid and started getting a 500 error.

When I accessed timber.scss.liquid directly, the contents of the file was

`"\xE2" from ASCII-8BIT to UTF-8 scss`

Not sure if relevant but I tried compiling the scss file locally and I kept on getting indentation errors

``` bash
$ sass timber.scss.liquid
Syntax error: Inconsistent indentation: 2 spaces were used for indentation, but the rest of the document was indented using 4 spaces.
        on line 18 of timber.scss.liquid
  Use --trace for backtrace.
```

I fixed this by adding `@charset "UTF-8";` to timber.scss.liquid.

**Comment by tyteen4a03** [comment]
This is still happening. Using 1.1.0.

http://cdn.shopify.com/s/files/1/0751/9403/t/2/assets/timber.scss.css?114

**Comment by tyteen4a03** [comment]
This is still happening. Using 2.0.1.

https://cdn.shopify.com/s/files/1/0751/9403/t/2/assets/timber.scss.css?453

**Comment by cshold** [comment]
No luck with that link @tyteen4a03. Any other info you can provide?

**Comment by sdn90** [comment]
Just ran bootstrap from the theme gem and got this error again.

**Comment by cshold** [comment]
The theme gem's bootstrap is currently bringing in an old version. We're looking at a fix for that. In the meantime, grab the latest from master here, or https://github.com/Shopify/Timber/releases/tag/v2.0.2
