### ISSUE TITLE
[feature request]Ajaxify Cart - Don't open drawer on adding to cart

### ISSUE THREAD

**Issue by r3wt** [Shopify/Timber#603]
I've reviewed the documentation and tried hooking several events, but can't seem to prevent the cart from opening.

**Comment by cshold** [comment]
[These lines](https://github.com/Shopify/Timber/blob/master/layout/theme.liquid#L430-L433) in `layout/theme.liquid` are what open the drawer after a product is added. Remove or comment them out and you should be set.
