### ISSUE TITLE
Multiple Versions of jQuery

### ISSUE THREAD

**Issue by wjbarber3** [Shopify/Timber#611]
Contributors,

My version of Timber is loaded 3 different versions of jQuery.  Is this needed?  I am trying to optimize the javascript delivery of my site and wondering if I can just use the latest version of jQuery instead of having multiple versions.  Is some of the javascript dependent on older versions of jQuery or can I safely remove?
<img width="770" alt="screen shot 2017-02-10 at 12 52 16 pm" src="https://cloud.githubusercontent.com/assets/8922074/22841703/ccfa2c9a-ef8f-11e6-816e-86ca19334149.png">

**Comment by cshold** [comment]
Can't say this is related to Timber (it only has one version included) so am going to close the comment.

That said, you shouldn't need or want three versions. I can't speak to the differences between the versions specifically but you should investigate why they're included — is an app including its own version, is it included in the theme code multiple times, etc — and ideally stick to one.
