### ISSUE TITLE
Quick View/Shop on Collection page with BuyButton.js?

### ISSUE THREAD

**Issue by ajmalafif** [Shopify/Timber#615]
Is this generally a good idea or there's actually a better idea like loading a product page in a modal instead? 

Not expecting a hand-guiding tutorial but appreciate some pointers. I'll share the solution here if I get there first, somehow.

**Comment by cshold** [comment]
The only way I've done it is to ajax

**Comment by ajmalafif** [comment]
@cshold ah i see, that's very helpful. I'll try that. I am okay if you want to close the issue but I'll be updating it until I found a solution to share!
