### ISSUE TITLE
Can we add ajaxify drawer on collection pages products and on front page products?

### ISSUE THREAD

**Issue by barjinder2014** [Shopify/Timber#616]
I have concern about brooklyn theme which has used the timber structure and I want to add drawer on collection pages product's add to cart button and same on home page products, as its working on single page product.

Anyone can help me on this, please?

**Comment by cshold** [comment]
Since this isn't a bug with Timber I'm going to close the issue. I'd recommend creating a post in our [design forums](https://ecommerce.shopify.com/c/ecommerce-design) for help with a request like this.
